apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-firefox-rep
spec:  
  replicas: 2
  selector:
    app: selenium-node-firefox
  template:
    metadata:
      name: selenium-node-firefox
      labels:
        app: selenium-node-firefox
    spec:
      containers:
        - name: selenium-node-firefox
          image: selenium/node-firefox
          ports:
            - containerPort: 5901
          env:
           - name:  HUB_HOST
             value: "selenium-srv" 
           - name: HUB_PORT
             value: "4444"